Revert "canvas: add basic support"
This reverts commit 7d6031cccba3744f9bef726fced8be9e624b54bd.

Break compile:

drivers/amlogic/canvas/canvas.c: In function ‘canvas_probe’:
drivers/amlogic/canvas/canvas.c:398:1: error: the frame size of 2568 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
cc1: all warnings being treated as errors

Change-Id: I18300fbaafce71fe453332afe55969e917e1f024